### ISSUE TITLE
Mod dont work with last game update (steam)

### ISSUE THREAD

**Issue by Segfault-Git** [DrFair/WallPumps#3]
Proofs!
[https://i.imgur.com/lUtMLU6.jpg](url)
[https://i.imgur.com/BXR7dMi.jpg](url)

**Comment by DrFair** [comment]
Either you have other mods that conflict with this one, or you have an older version of the mod.
You can check the version in the changelog.txt file located at:
C:\Users\%USERNAME%\Documents\Klei\OxygenNotIncluded\mods\Steam\1845579729
If the changelog has the latest version (2.1) then it's a conflicting mod.

**Comment by Segfault-Git** [comment]
Other mods DISABLED! Okay. Another screen WITHOUT ANY MOD!
![2019-10-07_134620](https://user-images.githubusercontent.com/3286315/66305829-dbe8fb80-e908-11e9-80b1-37d75d94f003.jpg)

**Comment by Segfault-Git** [comment]
[Changelog.txt](https://github.com/DrFair/WallPumps/files/3696799/Changelog.txt)

**Comment by DrFair** [comment]
Please post your output_log.txt file located at
%APPDATA%\\..\LocalLow\Klei\Oxygen Not Included

**Comment by Segfault-Git** [comment]
[output_log.txt](https://github.com/DrFair/WallPumps/files/3696824/output_log.txt)

**Comment by DrFair** [comment]
I am not able to replicate this in any way. Here's a few things to try:
Verify game files
Reinstall mod (By unsubscribing, launching game and resubscribing, maybe even delete the mod files)
Reinstall the game
Install mod manually from releases

**Comment by Segfault-Git** [comment]
i delete game, clear all files, install game, install mod manually - same problem with same log

[11:40:10.551] [1] [INFO] Loading mod content Animation [Wall Pumps and Vents:1845579729] (provides DLL, Animation)
[11:40:11.740] [1] [INFO]  === WallPumps v. 2.1 LoadGeneratedBuildings === 
NullReferenceException: Object reference not set to an instance of an object
at WallPumps.GasWallPump.Setup () <0x000a8>
at WallPumps.GeneratedBuildings_LoadGeneratedBuildings_Patch.Prefix () <0x000e6>
at (wrapper dynamic-method) GeneratedBuildings.LoadGeneratedBuildings_Patch1 (System.Collections.Generic.List`1<System.Type>) <0x00054>
at LegacyModMain.LoadBuildings (System.Collections.Generic.List`1<System.Type>) <0x000c4>
at LegacyModMain.Load () <0x0013a>
at Assets.CreatePrefabs () <0x00018>
at Assets.OnPrefabInit () <0x00d51>
at KMonoBehaviour.InitializeComponent () <0x00195>

Rethrow as Exception: Error in GameAssets(Clone).Assets.OnPrefabInit
  at KMonoBehaviour.InitializeComponent () [0x00000] in <filename unknown>:0 
  at KMonoBehaviour.Awake () [0x00000] in <filename unknown>:0 
UnityEngine.Object:Internal_InstantiateSingleWithParent_Injected(Object, Transform, Vector3&, Quaternion&)
UnityEngine.Object:Internal_InstantiateSingleWithParent(Object, Transform, Vector3, Quaternion)
UnityEngine.Object:Instantiate(Object, Vector3, Quaternion, Transform)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion, Transform)
Util:KInstantiate(GameObject, Vector3, Quaternion, GameObject, String, Boolean, Int32)
Util:KInstantiate(GameObject, GameObject, String)
LaunchInitializer:Update()
 
(Filename:  Line: -1)

**Comment by Segfault-Git** [comment]
=(

**Comment by DrFair** [comment]
Sorry about the late response.
I still haven't been able to replicate or figure out the cause of this problem.
A few questions that might help narrow it down:
Did you have the mod installed before the update that broke it for you? And did it work fine?
Has the mod generated a config file? Located at: 
`C:\Users\%USERNAME%\Documents\Klei\OxygenNotIncluded\mods\settings`
If not, does your computer username have odd characters? Like Russian etc.

**Comment by Segfault-Git** [comment]
1) mod worked fine! its helps me very well. i cant play without your mod now((
2) Yea. its generated. i know about it
3) C:\Users\Nuke\ (i know this problem with characters, so never use them. only eng)

i even try switch lang in ONI - same problem =(

**Comment by DrFair** [comment]
Can you upload a copy of your WallPumps.json settings file?
Try and delete it completely and launch the game again.

**Comment by andreisbarnea** [comment]
experienced the same problem:
- worked before the latest update
workaround:
- deleted the settings file and restarted the game

**Comment by Segfault-Git** [comment]
> 
> 
> experienced the same problem:
> 
>     * worked before the latest update
>       workaround:
> 
>     * deleted the settings file and restarted the game

I delete game with all mods/files/folder. Don`t work for me =(

**Comment by Segfault-Git** [comment]
> 
> 
> Can you upload a copy of your WallPumps.json settings file?
> Try and delete it completely and launch the game again.

it`s null bec i CANT install mod now =)

**Comment by andreisbarnea** [comment]
Maybe this helps: attached you can find the file that I deleted in order to make it work.
[WallPumps.zip](https://github.com/DrFair/WallPumps/files/3735082/WallPumps.zip)
